name: CI/CD

on: push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            # 下载源码
            - name: Checkout
              uses: actions/checkout@master

            # 打包构建
            - name: Build
              uses: actions/setup-node@master
            - run: yarn install
            - run: yarn run build
            - run: zip -q -r dist.zip ./dist

            - name: Get current date
              id: date
              run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

            # 发布 Release
            - name: Create Release
              id: create_release
              uses: actions/create-release@master
              env:
                  GITHUB_TOKEN: ${{ secrets.MU }}
              with:
                  tag_name: tag-${{ steps.date.outputs.date }}
                  release_name: release-${{ steps.date.outputs.date }}
                  draft: false
                  prerelease: false

            # 上传构建
            - name: Upload Release Asset
              uses: actions/upload-release-asset@master
              env:
                  GITHUB_TOKEN: ${{ secrets.MU }}
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: ./dist.zip
                  asset_name: dist.zip
                  asset_content_type: application/zip

            # 部署到服务器
            - name: Deploy
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USERNAME }}
                  password: ${{ secrets.SSH_PASSWORD }}
                  script: |
                      cd /home/website/whereismu/
                      rm -rf
                      wget https://github.com/allinisha/mu/releases/latest/download/dist.zip -O dist.zip
                      unzip dist.zip
                      pm2 reload all
